// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGW7Ua6aFqYYDumObAp-nNq8g5aTVZ7wU',
    appId: '1:777883723878:web:79a8005788bf078830a5a7',
    messagingSenderId: '777883723878',
    projectId: 'reminder-plus-new',
    authDomain: 'reminder-plus-new.firebaseapp.com',
    storageBucket: 'reminder-plus-new.firebasestorage.app',
    measurementId: 'G-P03N3SW9FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4zHi5KnCKn67fBiPxY2um3LtMxIf34B8',
    appId: '1:777883723878:android:0a30b57b2f1d54f030a5a7',
    messagingSenderId: '777883723878',
    projectId: 'reminder-plus-new',
    storageBucket: 'reminder-plus-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDm_omruifpGsJ0UmCZ7NZ21w4_P6BbAg',
    appId: '1:777883723878:ios:0dfdd4fd39bd960a30a5a7',
    messagingSenderId: '777883723878',
    projectId: 'reminder-plus-new',
    storageBucket: 'reminder-plus-new.firebasestorage.app',
    iosBundleId: 'com.reminder.reminderplus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDm_omruifpGsJ0UmCZ7NZ21w4_P6BbAg',
    appId: '1:777883723878:ios:cd9ff8b5b27d5c4530a5a7',
    messagingSenderId: '777883723878',
    projectId: 'reminder-plus-new',
    storageBucket: 'reminder-plus-new.firebasestorage.app',
    iosBundleId: 'com.example.reminderPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGW7Ua6aFqYYDumObAp-nNq8g5aTVZ7wU',
    appId: '1:777883723878:web:0ad761db442a8d9530a5a7',
    messagingSenderId: '777883723878',
    projectId: 'reminder-plus-new',
    authDomain: 'reminder-plus-new.firebaseapp.com',
    storageBucket: 'reminder-plus-new.firebasestorage.app',
    measurementId: 'G-7LHZMTDZ3G',
  );
}
